/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_AT = 4,
  anon_sym_storage = 5,
  anon_sym_EQ = 6,
  anon_sym_dense = 7,
  anon_sym_sparse = 8,
  anon_sym_flag = 9,
  anon_sym_limit = 10,
  sym_field = 11,
  sym_identifier = 12,
  sym_number = 13,
  sym_source_file = 14,
  sym_component = 15,
  sym_component_data = 16,
  sym_component_name = 17,
  sym_tag = 18,
  sym_tag_storage = 19,
  sym_tag_storage_value = 20,
  sym_tag_storage_limit = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_component_repeat1 = 23,
  aux_sym_component_repeat2 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT] = "@",
  [anon_sym_storage] = "storage",
  [anon_sym_EQ] = "=",
  [anon_sym_dense] = "dense",
  [anon_sym_sparse] = "sparse",
  [anon_sym_flag] = "flag",
  [anon_sym_limit] = "limit",
  [sym_field] = "field",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_component] = "component",
  [sym_component_data] = "component_data",
  [sym_component_name] = "component_name",
  [sym_tag] = "tag",
  [sym_tag_storage] = "tag_storage",
  [sym_tag_storage_value] = "tag_storage_value",
  [sym_tag_storage_limit] = "tag_storage_limit",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_component_repeat1] = "component_repeat1",
  [aux_sym_component_repeat2] = "component_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_storage] = anon_sym_storage,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_dense] = anon_sym_dense,
  [anon_sym_sparse] = anon_sym_sparse,
  [anon_sym_flag] = anon_sym_flag,
  [anon_sym_limit] = anon_sym_limit,
  [sym_field] = sym_field,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_component] = sym_component,
  [sym_component_data] = sym_component_data,
  [sym_component_name] = sym_component_name,
  [sym_tag] = sym_tag,
  [sym_tag_storage] = sym_tag_storage,
  [sym_tag_storage_value] = sym_tag_storage_value,
  [sym_tag_storage_limit] = sym_tag_storage_limit,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_component_repeat1] = aux_sym_component_repeat1,
  [aux_sym_component_repeat2] = aux_sym_component_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_storage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dense] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sparse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_limit] = {
    .visible = true,
    .named = false,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_component_data] = {
    .visible = true,
    .named = true,
  },
  [sym_component_name] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_storage] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_storage_value] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_storage_limit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '=', 30,
        '@', 28,
        '[', 26,
        ']', 27,
        'd', 4,
        'f', 12,
        'l', 10,
        's', 16,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'g') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'g') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(1);
      END_STATE();
    case 13:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(2);
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '@') ADVANCE(28);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_storage);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_dense);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_sparse);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_flag);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_limit);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_field);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '@' &&
          lookahead != '[') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_field);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@' &&
          lookahead != '[') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 23},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 23},
  [13] = {.lex_state = 23},
  [14] = {.lex_state = 23},
  [15] = {.lex_state = 23},
  [16] = {.lex_state = 23},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_storage] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_dense] = ACTIONS(1),
    [anon_sym_sparse] = ACTIONS(1),
    [anon_sym_flag] = ACTIONS(1),
    [anon_sym_limit] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(21),
    [sym_component] = STATE(10),
    [sym_component_name] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      anon_sym_LF,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_field,
    STATE(3), 1,
      aux_sym_component_repeat1,
    STATE(7), 1,
      sym_tag,
    STATE(4), 2,
      sym_component_data,
      aux_sym_component_repeat2,
  [26] = 8,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_field,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_LF,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    STATE(7), 1,
      sym_tag,
    STATE(9), 1,
      aux_sym_component_repeat1,
    STATE(5), 2,
      sym_component_data,
      aux_sym_component_repeat2,
  [52] = 6,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_field,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    STATE(7), 1,
      sym_tag,
    STATE(6), 2,
      sym_component_data,
      aux_sym_component_repeat2,
  [72] = 6,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_field,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(7), 1,
      sym_tag,
    STATE(6), 2,
      sym_component_data,
      aux_sym_component_repeat2,
  [92] = 6,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_AT,
    ACTIONS(34), 1,
      sym_field,
    STATE(7), 1,
      sym_tag,
    STATE(6), 2,
      sym_component_data,
      aux_sym_component_repeat2,
  [112] = 4,
    ACTIONS(39), 1,
      anon_sym_LF,
    STATE(8), 1,
      aux_sym_component_repeat1,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(41), 2,
      anon_sym_LBRACK,
      anon_sym_AT,
  [127] = 4,
    ACTIONS(19), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_component_repeat1,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(45), 2,
      anon_sym_LBRACK,
      anon_sym_AT,
  [142] = 4,
    ACTIONS(49), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_component_repeat1,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(52), 2,
      anon_sym_LBRACK,
      anon_sym_AT,
  [157] = 4,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_component_name,
    STATE(11), 2,
      sym_component,
      aux_sym_source_file_repeat1,
  [171] = 4,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    STATE(2), 1,
      sym_component_name,
    STATE(11), 2,
      sym_component,
      aux_sym_source_file_repeat1,
  [185] = 2,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(63), 3,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_AT,
  [195] = 2,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(67), 3,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_AT,
  [205] = 2,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(71), 3,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_AT,
  [215] = 2,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(75), 3,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_AT,
  [225] = 2,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym_field,
    ACTIONS(79), 3,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_AT,
  [235] = 3,
    ACTIONS(81), 1,
      anon_sym_storage,
    ACTIONS(83), 1,
      anon_sym_limit,
    STATE(15), 2,
      sym_tag_storage,
      sym_tag_storage_limit,
  [246] = 2,
    STATE(16), 1,
      sym_tag_storage_value,
    ACTIONS(85), 3,
      anon_sym_dense,
      anon_sym_sparse,
      anon_sym_flag,
  [255] = 1,
    ACTIONS(87), 1,
      anon_sym_RBRACK,
  [259] = 1,
    ACTIONS(89), 1,
      sym_identifier,
  [263] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
  [267] = 1,
    ACTIONS(93), 1,
      sym_number,
  [271] = 1,
    ACTIONS(95), 1,
      anon_sym_EQ,
  [275] = 1,
    ACTIONS(97), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 92,
  [SMALL_STATE(7)] = 112,
  [SMALL_STATE(8)] = 127,
  [SMALL_STATE(9)] = 142,
  [SMALL_STATE(10)] = 157,
  [SMALL_STATE(11)] = 171,
  [SMALL_STATE(12)] = 185,
  [SMALL_STATE(13)] = 195,
  [SMALL_STATE(14)] = 205,
  [SMALL_STATE(15)] = 215,
  [SMALL_STATE(16)] = 225,
  [SMALL_STATE(17)] = 235,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 255,
  [SMALL_STATE(20)] = 259,
  [SMALL_STATE(21)] = 263,
  [SMALL_STATE(22)] = 267,
  [SMALL_STATE(23)] = 271,
  [SMALL_STATE(24)] = 275,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_repeat2, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat2, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat2, 2, 0, 0), SHIFT_REPEAT(17),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_repeat2, 2, 0, 0), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_data, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_data, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_data, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_data, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_storage_value, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_storage_value, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_name, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_name, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_storage_limit, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_storage_limit, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_storage, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_storage, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [91] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ecs_component_registry(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ecs_component_registry",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 8,
      .patch_version = 2,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
